In [1]:
import numpy as np
import random

In [2]:
data = np.loadtxt("att48_d.txt")

In [3]:
# defining a cost function to find the distance between pth city and the qth city

def city_cost(p,q):
    cost = -data[p][q]
    
    return cost

In [4]:
# defining a Stochastic Search Algorithm to find the city nearest to the pth city
b = 4 
rho = 2 
T = 12 # Number of Iterations



def search_city(p, search_space):
    
    if (len(search_space) == 0):
        print("All cities visited. None left")
        return -1
    
    print("Length of Search Space: ", len(search_space))
    if (len(search_space) == 1):
        return search_space[0]
    
    
    pop_t = np.array([], dtype=int) # create a list of generated city samples from which to choose the best b samples
    
    initial_pop = np.empty((b,), dtype=int)
    for k in range(0,b):
        alpha = np.random.uniform(0, 1)
        
        initial_pop[k] = search_space[(int)(np.random.uniform(0, len(search_space)))]
    
    parent_pop = initial_pop
    
    
    for t in range(0,T):
        
        print("Interation ", t+1)
        
        pop_t = np.append(pop_t, parent_pop)
        
        print("Initial Population")
        print(parent_pop)
        
        # generating children by random walk
        random_walk_pop = np.empty((b,))
        print("Empty random_walk_pop")
        print(random_walk_pop)
        
        k = 0
        while k < b:
            random_exploit = np.random.choice([-1, 1])
 
    
            random_walk = pop_t[k] + random_exploit * np.random.randint(0, rho)
            

            if (random_walk not in search_space):
                print("Random Walk", random_walk)
                continue
            
            random_walk_pop[k] = random_walk

            k = k + 1
            
        pop_t = np.append(pop_t, random_walk_pop)
        
        print("Random Walk")
        print(pop_t)
            
        # generating children by random linear combination
        random_lin_pop = np.empty((b,), dtype=int)
        k = 0
        while k<b:
            alpha = np.random.uniform(0, 1)
            
            # random_lin_pop[k] = np.rint((1 - alpha) * np.random.choice(pop_t) + alpha * np.random.choice(pop_t))
            idx1 = pop_t[(int)(np.random.uniform(0,pop_t.shape[0]))]
            print("idx1 = ", idx1)
            
            idx2 = pop_t[(int)(np.random.uniform(0,pop_t.shape[0]))]
            print("idx2 = ", idx2)
            
            # idx = (int)(np.rint((1 - alpha) * pop_t[idx1] + alpha * pop_t[idx2]))
            idx = (int)(np.rint((1 - alpha) * idx1 + alpha * idx2))
            print("idx = ", idx)
            print("pop_t shape = ", pop_t.shape[0])
            
            # if (idx == p):
            if (idx not in search_space):
                print("Lin Combi")
                continue
                
            random_lin_pop[k] = idx
            
            k = k + 1
            
        pop_t = np.append(pop_t, random_lin_pop)
        
        print("Random Linear Combination")
        print(pop_t)
        
        # generating samples by random re-initialization
        # random_pop = np.random.randint(x_min, x_max, b, dtype=int)
        random_pop = np.empty((b,), dtype=int)
        for q in range(0,b):
            random_pop[q] = search_space[(int)(np.random.uniform(0,len(search_space)))]
        
        pop_t = np.append(pop_t, random_pop)    
        
        print('Random Sampling')
        print(pop_t)
        
        # Parent Selection: Tournaments
        
        
        for k in range(0,b):
            temp_parent = np.empty((10,))
            temp_index = np.empty((10,), dtype=int)
            for q in range(0, 10):
                temp_index[q] = (int)(np.random.choice(pop_t))
                temp_parent[q] = city_cost(p, temp_index[q])
            
            parent_pop[k] = temp_index[np.argmax(temp_parent)]
        
        print("Parent_pop")
        print(parent_pop)
        
        pop_t = np.array([])
        print("\n")
    
    print(parent_pop)
    parent_cost = np.empty((b,))
    for q in range(0,b):
        parent_cost[q] = city_cost(p, q)
    
    return int(parent_pop[np.argmax(parent_cost)])
        
    

In [14]:
search_space = list(range(0, data.shape[0]))



dist = 0

# Choose a random city as starting point
initial_pt = int(np.random.randint(0,data.shape[0]))
solution = [initial_pt]


pt = initial_pt
stop = 0
while stop < data.shape[0]:
    search_space.remove(pt)
    min_city = search_city(pt, search_space)
    
    
    if min_city == -1:
        solution.append(initial_pt)
        break
        
    solution.append(min_city)
    
    print("Nearest City: ", min_city)
    print("Current Solution:", solution)
    print("search space", search_space)
    
    dist = dist + data[pt][min_city]
    
    pt = min_city
    stop = stop + 1

dist += data[pt][initial_pt]

print("\n")

print("Final Solution: ", solution)
print("Total min Distance: ", dist)
    

Length of Search Space:  47
Interation  1
Initial Population
[39  4 24 36]
Empty random_walk_pop
[-3489. -7027. -3891. -7987.]
Random Walk
[39.  4. 24. 36. 38.  4. 25. 37.]
idx1 =  38.0
idx2 =  24.0
idx =  35
pop_t shape =  8
idx1 =  38.0
idx2 =  38.0
idx =  38
pop_t shape =  8
idx1 =  4.0
idx2 =  24.0
idx =  22
pop_t shape =  8
idx1 =  37.0
idx2 =  24.0
idx =  36
pop_t shape =  8
Random Linear Combination
[39.  4. 24. 36. 38.  4. 25. 37. 35. 38. 22. 36.]
Random Sampling
[39.  4. 24. 36. 38.  4. 25. 37. 35. 38. 22. 36. 13. 41. 45. 12.]
Parent_pop
[38 41 25 25]


Interation  2
Initial Population
[38 41 25 25]
Empty random_walk_pop
[-3489. -7027. -3891. -7987.]
Random Walk
[38. 41. 25. 25. 38. 41. 24. 25.]
idx1 =  25.0
idx2 =  41.0
idx =  40
pop_t shape =  8
idx1 =  24.0
idx2 =  24.0
idx =  24
pop_t shape =  8
idx1 =  25.0
idx2 =  25.0
idx =  25
pop_t shape =  8
idx1 =  25.0
idx2 =  25.0
idx =  25
pop_t shape =  8
Random Linear Combination
[38. 41. 25. 25. 38. 41. 24. 25. 40. 24. 25. 25.

In [ ]:
### End of CODE

In [6]:
# Rough Code below. Kindly ignore

In [104]:
solution = []
for pt in range(0,10):
    
    space = list(range(0, data.shape[0]))
    space.pop(pt)
    #print(space)
    min_city = search_city(pt, space)
    solution.append(min_city)
    print("Nearest City: ", min_city)
    

print("Solution: ", solution)
# for i in range(0, 10):
    # print(np.argmin(np.delete(data[i], i)))

Interation  1
Initial Population
[3 5 1 5]
Empty random_walk_pop
[-1205. -3588.    -0. -5163.]
Random Walk
[3. 5. 1. 5. 2. 4. 1. 6.]
idx1 =  5.0
idx2 =  1.0
idx =  2
pop_t shape =  8
idx1 =  2.0
idx2 =  2.0
idx =  2
pop_t shape =  8
idx1 =  4.0
idx2 =  2.0
idx =  3
pop_t shape =  8
idx1 =  5.0
idx2 =  2.0
idx =  3
pop_t shape =  8
Random Linear Combination
[3. 5. 1. 5. 2. 4. 1. 6. 2. 2. 3. 3.]
Random Sampling
[3. 5. 1. 5. 2. 4. 1. 6. 2. 2. 3. 3. 9. 5. 8. 5.]
Parent_pop
[8 8 2 5]


Interation  2
Initial Population
[8 8 2 5]
Empty random_walk_pop
[1. 8. 1. 7.]
Random Walk
[8. 8. 2. 5. 8. 8. 1. 5.]
idx1 =  2.0
idx2 =  5.0
idx =  2
pop_t shape =  8
idx1 =  5.0
idx2 =  1.0
idx =  4
pop_t shape =  8
idx1 =  8.0
idx2 =  8.0
idx =  8
pop_t shape =  8
idx1 =  8.0
idx2 =  5.0
idx =  6
pop_t shape =  8
Random Linear Combination
[8. 8. 2. 5. 8. 8. 1. 5. 2. 4. 8. 6.]
Random Sampling
[8. 8. 2. 5. 8. 8. 1. 5. 2. 4. 8. 6. 2. 3. 7. 6.]
Parent_pop
[8 8 8 8]


Interation  3
Initial Population
[8 8 8 8]
E

In [102]:
t1 = np.array([], dtype=int)
for pt in range(0,10):
    #pt = 1
    f = search_city(pt, search_space)
    
    next_pt = f["next_pt"]
    search_space = f["search_space"]
    
    t1 = np.append(t1, next_pt)
    
    print(f)
    print(city_cost(pt,next_pt))
    #print(np.min(data[0][1:]))
    #print("l = ", l)
    
print(t1)

Interation  1
Initial Population
[1 4 2 5]
Empty random_walk_pop
[-4727.    -0. -3588. -2012.]
Random Walk
[1. 4. 2. 5. 1. 5. 3. 4.]
idx1 =  4.0
idx2 =  1.0
idx =  3
pop_t shape =  8
idx1 =  2.0
idx2 =  5.0
idx =  5
pop_t shape =  8
idx1 =  5.0
idx2 =  1.0
idx =  2
pop_t shape =  8
idx1 =  4.0
idx2 =  4.0
idx =  4
pop_t shape =  8
Random Linear Combination
[1. 4. 2. 5. 1. 5. 3. 4. 3. 5. 2. 4.]
Random Sampling
[1. 4. 2. 5. 1. 5. 3. 4. 3. 5. 2. 4. 7. 8. 2. 9.]
Parent_pop
[7 8 7 8]


Interation  2
Initial Population
[7 8 7 8]
Empty random_walk_pop
[2. 4. 2. 5.]
Random Walk
[7. 8. 7. 8. 7. 8. 7. 7.]
idx1 =  7.0
idx2 =  8.0
idx =  8
pop_t shape =  8
idx1 =  7.0
idx2 =  7.0
idx =  7
pop_t shape =  8
idx1 =  7.0
idx2 =  8.0
idx =  7
pop_t shape =  8
idx1 =  8.0
idx2 =  7.0
idx =  8
pop_t shape =  8
Random Linear Combination
[7. 8. 7. 8. 7. 8. 7. 7. 8. 7. 7. 8.]
Random Sampling
[7. 8. 7. 8. 7. 8. 7. 7. 8. 7. 7. 8. 4. 5. 1. 2.]
Parent_pop
[8 8 8 8]


Interation  3
Initial Population
[8 8 8 8]
E

TypeError: 'int' object is not subscriptable

In [ ]:
# getting to the travelling stuff

np.random.seed(0)

start_pt = np.random.choice(search_space)
# print(start_pt)
current_pt = start_pt

salesman_path = np.array(start_pt, dtype=int)

j = 0
while(j != start_pt):
    
    print("\n")
    print("Current stop: ", current_pt)
    
    next_step = search_city(current_pt, search_space)
    
    next_pt = next_step["next_pt"]
    search_space = next_step["search_space"]
    
    salesman_path = np.append(salesman_path, next_pt)
    current_pt = next_pt

print("END")

In [667]:
print(5)

5


In [660]:
f = (int)(np.rint(1.3))
print(type(f))
print(a[f])

<class 'int'>
3


In [661]:
d = [2.4, 5.1]
d[1] = np.rint(d[1])
print(d)
#li.append(d)
#li

[2.4, 5.0]


In [662]:
for i in range(0,6):
    print(np.random.choice([-1,1]))

-1
-1
1
-1
1
-1


In [663]:
a = np.array([1,2,3])
b = a
print(b)
b[1] = 7
print(a)
print(b)
print((int)(5.6))

[1 2 3]
[1 7 3]
[1 7 3]
5


In [664]:
h = np.array([])
print(h)

[]


In [665]:
v = np.append(h,a)
print(h)
print(v)
print(a)
a[1] = 9
print(v)
print(a)

[]
[1. 7. 3.]
[1 7 3]
[1. 7. 3.]
[1 9 3]


In [666]:
v = np.random.randint(x_min, x_max, 5)
print(v.shape)

(5,)


In [43]:
print(np.random.choice(a,7))

[1 7 3 1 1 3 1]


In [114]:
f = np.random.choice([-1, 1])
print(type(int(f)))

<class 'int'>


In [488]:
f = np.empty((b,), dtype=int)
h = np.empty((b+5,), dtype=int)

for k in range(0,b):
    h[k] = f[k] + np.random.choice([-1, 1])

print(f)
print(h)

#print(f+h)

f[2] = f[3] + 2
print(f[2])
print(f)

[      -1        0        2        0 16842752 16843009]
[      -2       -1        1       -1 16842751 16843008       95      112
      111      112        0]
2
[      -1        0        2        0 16842752 16843009]


In [596]:
a = np.arange(0,10)
b = np.delete(a, 5)
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 6 7 8 9]


In [597]:
b = np.array([ele for ele in a if ele != 7])
print(b)

[0 1 2 3 4 5 6 8 9]


In [629]:
print(np.array(5))

5


In [631]:
d = dict();
d['str'] = "daptain"
d['num'] = 99
print(d)

{'str': 'daptain', 'num': 99}


In [12]:
a = list(range(0,5))
print(a)

[0, 1, 2, 3, 4]


In [47]:
a = [i for i in range(0,15) if i%2 == 0]
print(a)

print(a[3])
print(len(a))
a.remove(6)
print(a)
a.insert(3,7)
print(a)

print(a[-2:2])

a2 = np.array([i for i in range(0,15) if i%2 == 0])
b1 = np.select([a2 != 8], [a2])
print(b1)

b2 = np.delete(a2, 4)
print(b2)

[0, 2, 4, 6, 8, 10, 12, 14]
6
8
[0, 2, 4, 8, 10, 12, 14]
[0, 2, 4, 7, 8, 10, 12, 14]
[]
[ 0  2  4  6  0 10 12 14]
[ 0  2  4  6 10 12 14]


In [62]:
a = int(np.rint(2.3))
print(type(a))

<class 'int'>


In [113]:
a = [1,2,4]

print(3 not in a)
print(3 in a)

True
False


In [121]:
print(int(np.rint(0.9)))

1
